//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YasminsChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int msg_Id { get; set; }
        public int sender_Id { get; set; }
        public Nullable<int> recepient_Id { get; set; }
        public string msg_txt { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual User User { get; set; }
    }
}
