//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YasminsChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Message = new HashSet<Message>();
        }
    
        public int user_Id { get; set; }
        public string user_name { get; set; }
    
        public virtual ICollection<Message> Message { get; set; }
    }
}
